---
# handlers file for apache2

- name: restart apache2
  action: service name=apache2 state=restarted

- name: reload apache2
  action: service name=apache2 state=reloaded

- name: reload ufw
  ufw: state=reloaded
